# 项目信息
project:
  env: DEV

# 服务器配置
server:
  port: 8080

# Spring配置
spring:
  jackson:
    time-zone: GMT+8
    ## 默认日期格式化
    date-format: yyyy-MM-dd HH:mm

# logback信息配置
logback:
  level: INFO
  appender: ${project.env}

# dubbo配置
dubbo:
  timeout: 30000