# 项目信息
project:
  env: DEV

# 服务器配置
server:
  port: 8001

# Spring配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_test?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: GMT+8
    ## 默认日期格式化
    date-format: yyyy-MM-dd HH:mm

# MyBatis配置
mybatis:
  mapper-locations: classpath*:/mappers/*.xml #对应mappers映射xml文件的所在路径
  configuration:
    map-underscore-to-camel-case: true # 使用resultType时自动将下划线转为驼峰命名


# logback信息配置
logback:
  level: INFO
  appender: ${project.env}